name: Playwright CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      USER_AGENT: ${{ secrets.USER_AGENT }}
      TMDB_USERNAME: ${{ secrets.TMDB_USERNAME }}
      TMDB_PASSWORD: ${{ secrets.TMDB_PASSWORD }}
      REPORT_PORTAL_API_KEY: ${{ secrets.REPORT_PORTAL_API_KEY }}
      REPORT_PORTAL_ENDPOINT: ${{ secrets.REPORT_PORTAL_ENDPOINT }}
      REPORT_PORTAL_LAUNCH: ${{ secrets.REPORT_PORTAL_LAUNCH }}
      REPORT_PORTAL_PROJECT: ${{ secrets.REPORT_PORTAL_PROJECT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm install
           
      - run: npm run test
