name: Playwright CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
    
      BASE_URL: ${{ secrets.BASE_URL }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
      USER_AGENT: ${{ secrets.USER_AGENT }}
      TMDB_USERNAME: ${{ secrets.TMDB_USERNAME }}
      TMDB_PASSWORD: ${{ secrets.TMDB_PASSWORD }}
      

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm install
      - run: npm run test
